[package]
name = "nvlist"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
binary = { path = "../binary" }
enum-macros = { path = "../enum-macros" }
xdr = { path = "../xdr" }
