[package]
name = "xdr"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
binary = { path = "../binary" }
xdr-macros = { path = "../xdr-macros" }
